# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: root
    password: 806127059
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
upload:
  path: backend/images
jwt:
  secret:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
logging:
  level:
    org.springframework.web: trace
    org.hibernate: error

stripe:
  secret-key: sk_test_51OHikCAiCn0BUr4JphPdee0SEr99MRG7w7p9CV5XECs4chqWhg5vVx7Vr7lLvEgM47w5gqa9tH3sk8VHdyhxoGEn00pWP3ObX8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 890569205307-aej1pgl3a88v83frp5dqp6aegikci2jl.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://accounts.google.com/o/oauth2/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: email