# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/db
    username: root
    password: 806127059
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
upload:
  path: backend/images
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
logging:
  level:
    org.springframework.web: trace
    org.hibernate: error

stripe:
  secret-key: sk_test_51OHikCAiCn0BUr4JphPdee0SEr99MRG7w7p9CV5XECs4chqWhg5vVx7Vr7lLvEgM47w5gqa9tH3sk8VHdyhxoGEn00pWP3ObX8

  security:
    oauth2:
      resourceserver:
        git-hub:
          opaque-token:
            introspection-uri: ${GITHUB_INTROSPECTION_URI}
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
        facebook:
          opaque-token:
            introspection-uri: ${FACEBOOK_INTROSPECTION_URI}
            client-id: ${FACEBOOK_CLIENT_ID}
            client-secret: ${FACEBOOK_CLIENT_SECRET}
        google:
          opaque-token:
            introspection-uri: ${GOOGLE_INTROSPECTION_URI}
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
        azure:
          activedirectory:
            client-id: ${AZURE_CLIENT_ID}
            client-secret: ${AZURE_CLIENT_SECRET}
            authority-host: ${AZURE_AUTHORITY_HOST}
            tenant-id: ${AZURE_AUTHORITY_HOST}
        refirect-uri: http://localhost:8081/login
java:
  io:
    tmpdir: C:\DRIVERS
mail:
  host: smtp.gmail.com
  port: 587
  username: bogdan.grigorenko.jb@gmail.com
  password: ${PASSWORD_MAIL}
